# The name of our application
spring.application.name=scan-service


# The URL that tells Spring where our database is and what type it is
# jdbc = Java Database Connectivity (the standard way Java talks to databases)
# postgresql = the database type we are using (a real production database!)
# localhost = the database is running on our own machine
# 5432 = the default port PostgreSQL runs on
# scandb = the name of our specific database we created in pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/scandb

# Tells Spring which Java class knows how to talk to PostgreSQL
# Every database has its own driver - this is PostgreSQL's driver
spring.datasource.driver-class-name=org.postgresql.Driver

# The username to log into the database
# postgres is the default admin user
spring.datasource.username=postgres

# The password set during PostgreSQL installation (should use environment variables instead)
spring.datasource.password=password


# JPA / Hibernate Configuration
# JPA = Java Persistence API (the standard for database access in Java)
# Hibernate = the implementation of JPA that Spring Boot uses


# Tells Hibernate what to do with our database tables on startup
# update = look at our @Entity classes and automatically create or
#          update the database tables to match them
spring.jpa.hibernate.ddl-auto=update

# Print every SQL statement (INSERT, SELECT, UPDATE, DELETE) Hibernate generates to the IntelliJ console

spring.jpa.show-sql=true

# Formatting output
spring.jpa.properties.hibernate.format_sql=true

# Tells Hibernate which SQL dialect to use
# Our Java code stays exactly the same - just this one line changes!
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect